In [5]:
from pybaseball import statcast, standings, playerid_lookup, pitching_stats, batting_stats, statcast_pitcher, schedule_and_record
schedule_and_record(2023, 'ATL')

http://www.baseball-reference.com/teams/ATL/2023-schedule-scores.shtml

,Date,Tm,Home_Away,Opp,W/L,R,RA,Inn,W-L,Rank,GB,Win,Loss,Save,Time,D/N,Attendance,cLI,Streak,Orig. Scheduled
1,"Thursday, Mar 30",ATL,@,WSN,W,7.0,2.0,9.0,1-0,1.0,Tied,Luetge,Corbin,None,3:07,D,35756.0,.99,1,None
2,"Saturday, Apr 1",ATL,@,WSN,W,7.0,1.0,9.0,2-0,1.0,up 0.5,Strider,Gray,None,2:21,D,27529.0,1.08,2,None
3,"Sunday, Apr 2",ATL,@,WSN,L,1.0,4.0,9.0,2-1,2.0,0.5,Gore,Shuster,Finnegan,2:17,D,21440.0,1.09,-1,None
4,"Monday, Apr 3",ATL,@,STL,W,8.0,4.0,9.0,3-1,1.0,up 0.5,Morton,Woodford,None,2:46,N,37689.0,1.00,1,None
5,"Tuesday, Apr 4",ATL,@,STL,W,4.0,1.0,9.0,4-1,1.0,up 1.5,Dodd,Matz,Minter,2:20,N,36501.0,1.06,2,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
158,"Wednesday, Sep 27",ATL,Home,CHC,W-wo,6.0,5.0,10.0,102-56,1.0,up13.0,Chavez,Palencia,None,2:51,N,37246.0,.01,3,None
159,"Thursday, Sep 28",ATL,Home,CHC,W,5.0,3.0,9.0,103-56,1.0,up14.0,Wright,Stroman,Iglesias,2:43,N,40249.0,.01,4,None
160,"Friday, Sep 29",ATL,Home,WSN,L,6.0,10.0,9.0,103-57,1.0,up13.5,Weems,Hand,None,3:16,N,41481.0,.00,-1,None
161,"Saturday, Sep 30",ATL,Home,WSN,W,5.0,3.0,9.0,104-57,1.0,up15.0,Strider,Weems,Iglesias,3:00,N,41652.0,.00,1,None
162,"Sunday, Oct 1",ATL,Home,WSN,L,9.0,10.0,9.0,104-58,1.0,up14.0,Harvey,Tonkin,Finnegan,3:09,D,40697.0,.00,-1,None